on: ["push", "pull_request"]

name: Testing Coverage

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Use Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install Dependencies    
      run: pip install -r requirements.txt

    - name: Run Pytest
      run: pytest --cov --cov-report=xml

    - name: Upload to Codacy 
      run: python-codacity-coverage -r coverage.xml
      with:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
