on: ["push", "pull_request"]

name: Testing Coverage

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Use Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install Dependencies    
      run: pip install -r requirements.txt

    - name: Run Pytest
      run: pytest --cov --cov-report=xml

    - name: Test
      run: echo ${{ secrets.CODACY_PROJECT_TOKEN }}

    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
