on: ["push", "pull_request"]

name: Testing Coverage

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Use Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install Dependencies    
      run: pip install -r requirements.txt

    - name: Run Pytest
      run: pytest --cov --cov-report=xml

    - name: Coveralls
      uses: coverallsapp/github-action@v2